app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::get('getMoviesInfoFromDBPedia', 'TestController@getMoviesInfoFromDBPedia');
Route::get('getBooksInfoFromDBPedia', 'TestController@getBooksInfoFromDBPedia');

Route::get('login', 'HomeController@showLogin');
Route::get('user/logout', 'UserController@logout');

Route::get('user/facebook', 'UserController@loginFacebook');

Route::get('user/facebook-data', 'UserController@getFacebookData');
Route::get('proc', 'UserController@proc');

Route::get('privacy-policy', 'HomeController@showPrivacyPolcicy');

Route::get('movies/{movie_id}', 'MovieController@showMovie');
Route::get('books/{book_id}', 'BookController@showBook');

Route::group(array('before' => 'auth'), function()
{
    Route::get('/', 'HomeController@showIndex');

    Route::group(array('prefix' => 'users'), function(){

        Route::get('{user_id}', 'UserController@showUserHome');
        Route::get('{user_id}/movies', 'UserController@showUserMovies');
        Route::get('{user_id}/books', 'UserController@showUserBooks');
        Route::get('{user_id}/profile', 'UserController@showUserProfile');
    });
});

Route::get('get-movies-info','ProfileController@getMoviesInfo');
Route::get('get-books-info','ProfileController@getBooksInfo');

Route::get('template', function(){
    return View::make('template');
});

app/models/Book.php
<?php


class Book extends Eloquent {

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'books';

    public function user()
    {
        return $this->belongsTo('User');
    }

    /***
     * Return all genres from a genre
     */
    public function genres()
    {
        return $this->belongsToMany('Genre', 'books_genres', 'books_id', 'genres_id');
    }

    public function getYearAttribute(){
        if(!$this->released or $this->released == '0000-00-00')
            return null;
        $date = DateTime::createFromFormat("Y-m-d", $this->released);

        return $date->format("Y");
    }

    public function genresToString(){
        return implode(', ', $this->genres->lists('name'));
    }

    public function country()
    {
        return $this->belongsTo('Country', 'countries_id');
    }
}

app/views/book.blade.php
@extends('layout.default')

@section('page-title')
{{ $book->title }}
@stop

@section('scripts')
@stop

@section('content')
<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Livro</h2>

    <div class="col-sm-3 col-md-3 col-xs-6" style="width: 100%">
        <div class="pull-left">
            <img src="https://graph.facebook.com/{{ $book->facebook_id }}/picture?width=200&height=312" class="img-thumbnail" />
        </div>
        <div style="padding: 0 10px; overflow: hidden">
            <div class="pull-right" style="margin-top: 15px">
                @for($i = 0; $i < $book->rating; $i++)
                <i class="fa fa-star" style="color: #FFD700"></i>
                @endfor
                @for(; $i < 5; $i++)
                <i class="fa fa-star"></i>
                @endfor
            </div>
            <h1 style="margin: 0">{{ $book->title }} <small>{{ $book->year }}</small></h1>

            <p class="lead">
                Autor: {{ $book->author }}
            </p>

            <p>{{ $book->abstract }}</p>

            <p><strong>País:</strong> {{ $book->country->name }}</p>

            <p><strong>Gêneros:</strong> {{ $book->genresToString() }}</p>

            <p><strong>Data de Lançamento:</strong> {{ date('d/m/Y', strtotime( $book->release_date )) }}</p>
        </div>

    </div>
</div>
@stop

app/views/index.blade.php
@extends('layout.default')

@section('page-title')
    User Model
@stop

@section('content')

@stop

app/views/login.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>User Model</title>
    {{ HTML::style('assets/css/bootstrap.min.css') }}
    {{ HTML::style('assets/css/font-awesome.min.css') }}
    {{ HTML::style('assets/css/bigvideo.css') }}
    {{ HTML::style('assets/usermodel/css/login.css') }}
</head>
<body style="background-image: url( {{ URL::to('assets/images/bookcase.jpg') }}); background-repeat: repeat-x; background-position: center top;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="page-section">
                    <h2>
                        Modelo de Usuário Automatizado
                    </h2>

                    <a href="{{ URL::to('/user/facebook') }}" class="btn btn-block btn-social btn-facebook" style="text-align: center; font-weight: bold;">
                        <i class="fa fa-facebook"></i> Login Facebook
                    </a>
                </div>

            </div>
        </div>
    </div>
</body>

    {{ HTML::script('assets/js/jquery.min.js') }}
    {{ HTML::script('assets/js/jquery-ui.min.js') }}
</html>

app/views/movie.blade.php
@extends('layout.default')

@section('page-title')
{{ $movie->title }}
@stop

@section('scripts')
@stop

@section('content')
<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Filme</h2>

    <div class="col-sm-3 col-md-3 col-xs-6" style="width: 100%">
        <div class="pull-left">
            <img src="https://graph.facebook.com/{{ $movie->facebook_id }}/picture?width=200&height=312" class="img-thumbnail" />
        </div>
        <div style="padding: 0 10px; overflow: hidden">
            <div class="pull-right" style="margin-top: 15px">
                @for($i = 0; $i < $movie->rating; $i++)
                <i class="fa fa-star" style="color: #FFD700"></i>
                @endfor
                @for(; $i < 5; $i++)
                <i class="fa fa-star"></i>
                @endfor
            </div>
            <h1 style="margin: 0">{{ $movie->title }} <small>{{ $movie->year }}</small></h1>

            <p class="lead">
                Dirigido por: {{ $movie->director }}
            </p>

            <p>{{ $movie->abstract }}</p>

            <p><strong>País:</strong> {{ $movie->country->name }}</p>

            <p><strong>Gêneros:</strong> {{ $movie->genresToString() }}</p>

            <p><strong>Data de Lançamento:</strong> {{ date('d/m/Y', strtotime( $movie->release_date )) }}</p>
        </div>

    </div>
</div>
@stop

app/views/privacy-policy.blade.php
@extends('layout.default')

@section('page-title')
Privacy Policy
@stop

@section('meta')
// faecbook meta-tags
<meta property="og:title" content="User Model"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="http://www.saindo.com.br/privacy-policy"/>
<meta property="og:image" content="{{ asset('assets/images/favicon.png') }}"/>
<meta property="og:site_name" content="User Model"/>
<meta property="og:description"
      content="Other Personal Data collected may be described in other sections of this privacy policy or by dedicated explanation text contextually with the Data collection.The Personal Data may be freely provided by the User, or collected automatically when using this Application.Any use of Cookies - or of other…"/>
@stop

@section('content')
<div class="features_items">

    <div class="col-sm-12" style="width: 100%">
<div class="iub_content legal_pp">
<div class="iub_header">
<h1>Privacy Policy of the <strong>UserModel</strong> Facebook app</h1>
<p>This Application collects some Personal Data from its Users.</p>
</div>
<div class="one_line_col">
<h2>Data Controller and Owner</h2>
</div>
<div class="one_line_col">
<h2>Types of Data collected</h2>
<p>The owner does not provide a list of Personal Data types collected.</p>
<p>Other Personal Data collected may be described in other sections of this privacy policy or by dedicated explanation text contextually with the Data collection.<br>The Personal Data may be freely provided by the User, or collected automatically when using this Application.<br>Any use of Cookies - or of other tracking tools - by this Application or by the owners of third party services used by this Application, unless stated otherwise, serves to identify Users and remember their preferences, for the sole purpose of providing the service required by the User.<br>Failure to provide certain Personal Data may make it impossible for this Application to provide its services.</p>
<p>Users are responsible for any Personal Data of third parties obtained, published or shared through this Application and confirm that they have the third party's consent to provide the Data to the Owner.</p>
</div>
<div class="one_line_col">
<h2>Mode and place of processing the Data</h2>
<h3>Methods of processing</h3>
<p>The Data Controller processes the Data of Users in a proper manner and shall take appropriate security measures to prevent unauthorized access, disclosure, modification, or unauthorized destruction of the Data.<br>The Data processing is carried out using computers and/or IT enabled tools, following organizational procedures and modes strictly related to the purposes indicated. In addition to the Data Controller, in some cases, the Data may be accessible to certain types of persons in charge, involved with the operation of the site (administration, sales, marketing, legal, system administration) or external parties (such as third party technical service providers, mail carriers, hosting providers, IT companies, communications agencies) appointed, if necessary, as Data Processors by the Owner. The updated list of these parties may be requested from the Data Controller at any time.</p>
<h3>Place</h3>
<p>The Data is processed at the Data Controller's operating offices and in any other places where the parties involved with the processing are located. For further information, please contact the Data Controller.</p>
<h3>Retention time</h3>
<p>The Data is kept for the time necessary to provide the service requested by the User, or stated by the purposes outlined in this document, and the User can always request that the Data Controller suspend or remove the data.</p>
</div>
<div class="one_line_col">
<h2>The use of the collected Data</h2>
<p>
The Data concerning the User is collected to allow the Owner to provide its services, as well as for the following purposes:
Access to third party services' accounts.
</p>
<p>The Personal Data used for each purpose is outlined in the specific sections of this document.</p>
</div>
<div class="one_line_col">
<h2>Facebook permissions asked by this Application</h2>
<p>This Application may ask for some Facebook permissions allowing it to perform actions with the User's Facebook account and to retrieve information, including Personal Data, from it.</p>
<p>For more information about the following permissions, refer to the <a target="_blank" href="https://developers.facebook.com/docs/authentication/permissions/">Facebook permissions documentation</a> and to the <a target="_blank" href="https://www.facebook.com/about/privacy/">Facebook privacy policy</a>.</p>
<p>The permissions asked are the following:</p>
<h3>Basic information</h3>
<p>By default, this includes certain User’s Data such as id, name, picture, gender, and their locale. Certain connections of the User, such as the Friends, are also available. If the user has made more of their data public, more information will be available.</p>
<h3>Books Actions</h3>
<h3>Email</h3>
<p>Provides access to the user's primary email address</p>
</div>
<div class="one_line_col">
<h2>Detailed information on the processing of Personal Data</h2>
<p>Personal Data is collected for the following purposes and using the following services:</p>
<ul class="for_boxes">
<li>
<div class="box_primary box_10 expand collapsed">
<h3 class="expand-click w_icon_24 policyicon_purpose_395724">Access to third party services' accounts</h3>
<div class="expand-content" style="display: none;">
<p>These services allow this Application to access Data from your account on a third party service and perform actions with it.<br>
These services are not activated automatically, but require explicit authorization by the User.</p>
<h4>Access to the Facebook account (This Application)</h4>
<p>This service allows this Application to connect with the User's account on the Facebook social network, provided by Facebook Inc.</p>
<p>
Permissions asked:
Books Actions and Email.
</p>
<p>
Place of processing
: USA
&ndash;
<a target="_blank" href="https://www.facebook.com/policy.php">Privacy Policy</a>
</p>
</div>
</div>
</li>
</ul>
</div>
<div class="one_line_col">
<h2>Additional information about Data collection and processing</h2>
<h3>Legal action</h3>
<p>
The User's Personal Data may be used for legal purposes by the Data Controller, in Court or in the stages leading to possible legal action arising from improper use of this Application or the related services.<br>The User declares to be aware that the Data Controller may be required to reveal personal data upon request of public authorities.
</p>
<h3>Additional information about User's Personal Data</h3>
<p>
In addition to the information contained in this privacy policy, this Application may provide the User with additional and contextual information concerning particular services or the collection and processing of Personal Data upon request.
</p>
<h3>System Logs and Maintenance</h3>
<p>
For operation and maintenance purposes, this Application and any third party services may collect files that record interaction with this Application (System Logs) or use for this purpose other Personal Data (such as IP Address).
</p>
<h3>Information not contained in this policy</h3>
<p>
More details concerning the collection or processing of Personal Data may be requested from the Data Controller at any time. Please see the contact information at the beginning of this document.
</p>
<h3>The rights of Users</h3>
<p>
Users have the right, at any time, to know whether their Personal Data has been stored and can consult the Data Controller to learn about their contents and origin, to verify their accuracy or to ask for them to be supplemented, cancelled, updated or corrected, or for their transformation into anonymous format or to block any data held in violation of the law, as well as to oppose their treatment for any and all legitimate reasons. Requests should be sent to the Data Controller at the contact information set out above.
</p>
<p>
This Application does not support “Do Not Track” requests.<br>To determine whether any of the third party services it uses honor the “Do Not Track” requests, please read their privacy policies.
</p>
<h3>Changes to this privacy policy</h3>
<p>
The Data Controller reserves the right to make changes to this privacy policy at any time by giving notice to its Users on this page. It is strongly recommended to check this page often, referring to the date of the last modification listed at the bottom. If a User objects to any of the changes to the Policy, the User must cease using this Application and can request that the Data Controller removes the Personal Data. Unless stated otherwise, the then-current privacy policy applies to all Personal Data the Data Controller has about Users.
</p>
<h3>Information about this privacy policy</h3>
<p>
The Data Controller is responsible for this privacy policy, prepared starting from the modules provided by Iubenda and hosted on Iubenda's servers.
</p>
</div>
<div class="one_line_col">
<div class="box_primary box_10 definitions expand expanded">
<h3 class="expand-click w_icon_24 icon_ribbon">
Definitions and legal references
</h3>
<div class="expand-content" style="display: block;">
<h4>Personal Data (or Data)</h4>
<p>Any information regarding a natural person, a legal person, an institution or an association, which is, or can be, identified, even indirectly, by reference to any other information, including a personal identification number.</p>
<h4>Usage Data</h4>
<p>Information collected automatically from this Application (or third party services employed in this Application ), which can include: the IP addresses or domain names of the computers utilized by the Users who use this Application, the URI addresses (Uniform Resource Identifier), the time of the request, the method utilized to submit the request to the server, the size of the file received in response, the numerical code indicating the status of the server's answer (successful outcome, error, etc.), the country of origin, the features of the browser and the operating system utilized by the User, the various time details per visit (e.g., the time spent on each page within the Application) and the details about the path followed within the Application with special reference to the sequence of pages visited, and other parameters about the device operating system and/or the User's IT environment.</p>
<h4>User</h4>
<p>The individual using this Application, which must coincide with or be authorized by the Data Subject, to whom the Personal Data refer.</p>
<h4>Data Subject</h4>
<p>The legal or natural person to whom the Personal Data refers.</p>
<h4>Data Processor (or Data Supervisor)</h4>
<p>The natural person, legal person, public administration or any other body, association or organization authorized by the Data Controller to process the Personal Data in compliance with this privacy policy.</p>
<h4>Data Controller (or Owner)</h4>
<p>The natural person, legal person, public administration or any other body, association or organization with the right, also jointly with another Data Controller, to make decisions regarding the purposes, and the methods of processing of Personal Data and the means used, including the security measures concerning the operation and use of this Application. The Data Controller, unless otherwise specified, is the Owner of this Application.</p>
<h4>This Application</h4>
<p>The hardware or software tool by which the Personal Data of the User is collected.</p>
<hr>
<h4>Legal information</h4>
<p>Notice to European Users: this privacy statement has been prepared in fulfillment of the obligations under Art. 10 of EC Directive n. 95/46/EC, and under the provisions of Directive 2002/58/EC, as revised by Directive 2009/136/EC, on the subject of Cookies.</p>
<p>This privacy policy relates solely to this Application.</p>
</div>
</div>
</div>
<div class="iub_footer">
<p>
Latest update: May 02, 2015
</p>

</div>

    </div>
</div>
@stop

app/views/test.blade.php
<pre>
    {{{ print_r($data) }}}
</pre>